//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuseumApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActInstance
    {
        public int ActInstanceId { get; set; }
        public int OrganizationId { get; set; }
        public int MovementActId { get; set; }
        public int MuseumFondId { get; set; }
    
        public virtual MovementAct MovementAct { get; set; }
        public virtual MuseumFond MuseumFond { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
