//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuseumApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovementAct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MovementAct()
        {
            this.ActInstance = new HashSet<ActInstance>();
        }
    
        public int MovementActId { get; set; }
        public int EmpId { get; set; }
        public int ItemsSetId { get; set; }
        public int ItemStateId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActInstance> ActInstance { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ItemsSet ItemsSet { get; set; }
        public virtual ItemState ItemState { get; set; }
    }
}
