//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuseumApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MuseumDataBaseEntities : DbContext
    {
        public MuseumDataBaseEntities()
            : base("name=MuseumDataBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActInstance> ActInstance { get; set; }
        public virtual DbSet<Author> Author { get; set; }
        public virtual DbSet<ContactPerson> ContactPerson { get; set; }
        public virtual DbSet<DateType> DateType { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Exhibition> Exhibition { get; set; }
        public virtual DbSet<Item> Item { get; set; }
        public virtual DbSet<ItemInstance> ItemInstance { get; set; }
        public virtual DbSet<ItemsHistory> ItemsHistory { get; set; }
        public virtual DbSet<ItemsSet> ItemsSet { get; set; }
        public virtual DbSet<ItemState> ItemState { get; set; }
        public virtual DbSet<MovementAct> MovementAct { get; set; }
        public virtual DbSet<MuseumFond> MuseumFond { get; set; }
        public virtual DbSet<Organization> Organization { get; set; }
        public virtual DbSet<SetInstance> SetInstance { get; set; }
    }
}
