//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuseumApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetInstance
    {
        public int SetInstanceId { get; set; }
        public int ItemId { get; set; }
        public int ItemsSetId { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual ItemsSet ItemsSet { get; set; }
    }
}
